### PR TITLE
Fix #303

### LINKED ISSUE #303: Incorrectly outdated targets after loadd()
Calling `loadd()` changes `outdated(drake_config(plan))`, but not `outdated(read_drake_config())`. This doesn't happen if `x` is created from a constant such as `42`.

``` r
writeLines("test", "test.txt")

pkgload::load_all("testpkg")
#> Loading testpkg
library(drake)
plan <- drake_plan(
  x = readLines(file_in("test.txt")),
  strings_in_dots = "literals"
)
make(plan)
#> cache /tmp/RtmpArc3UM/.drake
#> connect 1 import: plan
#> connect 1 target: x
#> check 2 items: file "test.txt", readLines
#> check 1 item: x
#> target x
outdated(read_drake_config())
#> cache /tmp/RtmpArc3UM/.drake
#> check 2 items: file "test.txt", readLines
#> unload 1 item: x
#> check 1 item: x
#> character(0)
outdated(drake_config(plan))
#> cache /tmp/RtmpArc3UM/.drake
#> connect 1 import: plan
#> connect 1 target: x
#> check 2 items: file "test.txt", readLines
#> check 1 item: x
#> character(0)
loadd()
#> cache /tmp/RtmpArc3UM/.drake
outdated(read_drake_config())
#> cache /tmp/RtmpArc3UM/.drake
#> check 2 items: file "test.txt", readLines
#> unload 1 item: x
#> check 1 item: x
#> character(0)
outdated(drake_config(plan))
#> cache /tmp/RtmpArc3UM/.drake
#> connect 10 imports: close, file "testpkg/DESCRIPTION", UseMethod, is.cha...
#> connect 1 target: x
#> check 5 items: .Internal, file "test.txt", is.character, on.exit, UseMethod
#> check 2 items: close, file
#> check 1 item: readLines
#> check 1 item: x
#> [1] "x"
rm(x)
#> Warning in rm(x): object 'x' not found
outdated(read_drake_config())
#> cache /tmp/RtmpArc3UM/.drake
#> check 2 items: file "test.txt", readLines
#> check 1 item: x
#> character(0)
outdated(drake_config(plan))
#> cache /tmp/RtmpArc3UM/.drake
#> connect 10 imports: close, file "testpkg/DESCRIPTION", UseMethod, is.cha...
#> connect 1 target: x
#> check 5 items: .Internal, file "test.txt", is.character, on.exit, UseMethod
#> check 2 items: close, file
#> check 1 item: readLines
#> check 1 item: x
#> [1] "x"
make(plan)
#> cache /tmp/RtmpArc3UM/.drake
#> connect 10 imports: close, file "testpkg/DESCRIPTION", UseMethod, is.cha...
#> connect 1 target: x
#> check 5 items: .Internal, file "test.txt", is.character, on.exit, UseMethod
#> check 2 items: close, file
#> check 1 item: readLines
#> check 1 item: x
#> target x
outdated(read_drake_config())
#> cache /tmp/RtmpArc3UM/.drake
#> check 5 items: .Internal, file "test.txt", is.character, on.exit, UseMethod
#> unload 1 item: x
#> check 2 items: close, file
#> check 1 item: readLines
#> check 1 item: x
#> character(0)
```

> Created on 2018-03-06 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

### PR DESCRIPTION
**Pull request by wlandau**
# Summary

- In `loadd()`, exclude foreign imports: i.e., imports that were not explicitly taken from `envir`. Foreign imports can come from a package or an ancestor of `envir`.
- in `flexible_get()`, don't just `get(target)`. Use `get(target, envir)` to be sure that `flexible_get()` searches for `target` in `envir`, an ancestor of `envir`, or possibly a package. That way, `drake` does not creep into the global environment uninvited. This change could invalidate targets for strangely-configured workflows, and most users are not likely to notice it.

# GitHub issues fixed

- Ref: #303

# Checklist

- [x] I have read `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CONDUCT.md), and I agree to follow its rules.
- [x] I have read the [guidelines for contributing](https://github.com/ropensci/drake/blob/master/CONTRIBUTING.md).
- [x] I have listed any substantial changes in the [development news](https://github.com/ropensci/drake/blob/master/NEWS.md).
- [x] I have added [`testthat`](https://github.com/r-lib/testthat) unit tests to [`tests/testthat`](https://github.com/ropensci/drake/tree/master/tests/testthat) to confirm that any new features or functionality work correctly.
- [x] I have tested this pull request locally with `devtools::check()`
- [x] This pull request is ready for review and/or merge.

### CODE REVIEW

File: R/meta.R [hunk 1]
```diff
@@ -64,6 +64,7 @@ drake_meta <- function(target, config = drake::read_drake_config()) {
   meta <- list(
     target = target,
     imported = !(target %in% config$plan$target),
+    foreign = !(target %in% ls(config$envir)),
```
Comment (krlmlr) [inline R/meta.R]: `exists()` might be faster here.

File: R/read.R [hunk 2]
```diff
@@ -214,6 +224,30 @@ loadd <- function(
...
+  }
+  meta <- diagnose(
+    target = target,
+    cache = cache,
+    character_only = TRUE,
+    verbose = FALSE
+  )
+  identical(meta$imported, FALSE) ||
+    identical(meta$foreign, FALSE) ||
+    is_file(target)
```
Comment (krlmlr) [inline R/read.R]: Do we need to call `diagnose()` if `is_file(target)` ?

File: R/read.R [hunk 3]
```diff
@@ -206,6 +211,11 @@ loadd <- function(
   if (!replace){
     targets <- setdiff(targets, ls(envir, all.names = TRUE))
   }
+  targets <- exclude_foreign_imports(
```
Comment (krlmlr) [inline R/read.R]: The changes in this function conceptually seem to fit better in `drake_select()`. Do we really need `build_times()` or `clean()` for imported targets (these are other callers of `drake_select()`)? Does that function have access to all relevant information?

File: R/meta.R (hunk 1 above)
Comment (wlandau) [reply R/meta.R]: I tried `exists()` at first, but it also includes the ancestors of `envir`, so I was getting bad results. But you're right in the sense that slow set operations are too widespread throughout the code. I do want to change that at some point.

File: R/read.R (hunk 2 above)
Comment (wlandau) [reply R/read.R]: Imported files do not have the problem in #303, so that line includes them. The `is_file(target)` makes the new behavior agree with the old behavior when possible. I do think we should think about excluding files in general from `loadd()`, but I think it is out of scope of this PR.

File: R/read.R (hunk 3 above)
Comment (wlandau) [reply R/read.R]: To answer both this question and your first question: the only reason to worry about foreign imports is #303, where we risk putting a function in an environment where it does not belong. The only API function with this problem is `loadd()`.

Another thing: I really think we should screen for foreign imports towards the end of `loadd()` rather than in `drake_select()` because that's the only place we have the actual list of targets. For example, if the `deps` argument is `TRUE`, we are actually loading the *dependencies* of the items enumerated with `drake_select()`.

File: R/meta.R (hunk 1 above)
Comment (krlmlr) [reply R/meta.R]: `exists(inherits = FALSE)` perhaps?

File: R/read.R (hunk 2 above)
Comment (krlmlr) [reply R/read.R]: Can we check `is_file()` without invoking `diagnose()`?

Comment (wlandau) [reply R/read.R]: Yes: 2d1180b3c214922689aff1d636e8d871390c00b4.

File: R/meta.R (hunk 1 above)
Comment (wlandau) [reply R/meta.R]: Yes: 2d1180b3c214922689aff1d636e8d871390c00b4.

**Comment by wlandau** [comment]
Seems like we can merge now and make minor adjustments going forward. Thanks for the feedback, as always.
